### PR TITLE
Surface floating-point operation errors in Github CI

### PR DESCRIPTION
**Pull request by danielhollas**
To catch issues like #48. The tests are now failing, as they should, so this should be merged only once the #48 is addressed.

Some context can be find here:
https://docs.oracle.com/cd/E19957-01/805-4940/6j4m1u7pj/index.html

FYI: @suchanj

### CODE REVIEW

**Comment by suchanj** [comment]
#48 fixed, rebased, ready to merge.
However, codecov reports src/plumed.F90 coverage -96.67%, could you check that?

**Comment by danielhollas** [comment]
Thanks!

Weird, this PR does not touch any Fortran code so coverage should not be affected. Maybe some bad interaction between the compiler flags? I'll take a look.

**Comment by suchanj** [comment]
Codecov now looks ok, ready to merge?

**Comment by danielhollas** [comment]
I'm working on cleaning up those compiler warnings, wanted to do that as
part of this PR, but maybe I'll do it in a separate one.

Dne po 4. 1. 2021 10:35 dop. uživatel Jiri Suchan <notifications@github.com>
napsal:

**Comment by danielhollas** [comment]
Merging now, will open a new PR that will fix the compiler warnings.

**Pull request merged**
